AllCops:
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

LineLength:
  Max: 130

MethodLength:
  Max: 20

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false
