name             'rails_part'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures rails_part'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'cloudconductor'
depends 'git'
depends 'build-essential'
depends 'rbenv'
depends 'application'
depends 'application_ruby'
depends 'puma'
depends 'yum-mysql-community'
