#!/bin/env ruby
# -*- coding: utf-8 -*-
# Copyright 2014 TIS Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if __FILE__ == $PROGRAM_NAME
  require 'logger'
  require 'pathname'
  require_relative '../user_action_base'
  logger = Logger.new('/tmp/user-action.log')
  current_directory = File.expand_path(File.dirname(__FILE__))
  role = current_directory.split('/').last
  event_name = File.basename(__FILE__).split('-').last
  additional_parameters = {
    serf: {
      agent: {
        tags: {
          role: ENV['SERF_TAG_ROLE']
        }
      }
    }
  }
  logger.debug("role = #{role}")
  logger.debug("event_name = #{event_name}")
  logger.debug("additional_parameters = #{additional_parameters}")

  UserActionBase.new(role, event_name, additional_parameters).execute(true)

  script_name = File.expand_path(__FILE__)
  logger.debug("script_name = #{script_name}")

  parent_directory = Pathname.new(current_directory).parent
  logger.debug("parent_directory = #{parent_directory}")
  Dir.glob("#{parent_directory}/**/user-setup") do |user_setup_script|
    logger.debug("user_setup_script = #{user_setup_script}")
    if user_setup_script == script_name
      logger.debug("#{user_setup_script} is itself. skipped.")
      next
    else
      logger.debug("execute #{user_setup_script}.")
    end
    user_setup_script_result = system(user_setup_script)
    logger.debug("user_setup_script_result = #{user_setup_script_result}")
  end
end
