#!/bin/env ruby
# -*- coding: utf-8 -*-
# Copyright 2014 TIS Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if __FILE__ == $PROGRAM_NAME
  require_relative '../user_action_base'
  current_directory = File.expand_path(File.dirname(__FILE__))
  role = current_directory.split('/').last
  event_name = File.basename(__FILE__).split('-').last
  additional_parameters = {
    serf: {
      agent: {
        tags: {
          role: ENV['SERF_TAG_ROLE']
        }
      }
    }
  }
  UserActionBase.new(role, event_name, additional_parameters).execute(true)
end
