db:
  paths:
    - path: /var/cloudconductor/backups/mysql
      prepare_path: true
      schedule: "0 0 * * *"
      script:
        pre_backup: ! '(source /opt/cloudconductor/config; CONSUL_SECRET_KEY_ENCODED="`/opt/chefdk/embedded/bin/ruby -e \"require ''cgi''; puts CGI::escape(''${CONSUL_SECRET_KEY}'')\"`"; SALT="`curl -X GET http://localhost:8500/v1/kv/cloudconductor/parameters?token=${CONSUL_SECRET_KEY_ENCODED} | jq ''.[].Value'' | sed -e ''s/[^\"]*\"\([^\"]*\)\".*/\1/'' | base64 -d | jq ''.cloudconductor.salt'' | sed -e ''s/[^\"]*\"\([^\"]*\)\".*/\1/''`"; PASSWORD="`/opt/chefdk/embedded/bin/ruby -e \"require ''openssl''; puts OpenSSL::Digest::SHA256.hexdigest(''${SALT}'' + ''database'')\"`"; sudo -u mysql mysqldump -u application -p${PASSWORD} -x --all-databases > /var/cloudconductor/backups/mysql/dump.sql) >/dev/null 2>&1'
        post_restore: ! '(source /opt/cloudconductor/config; CONSUL_SECRET_KEY_ENCODED="`/opt/chefdk/embedded/bin/ruby -e \"require ''cgi''; puts CGI::escape(''${CONSUL_SECRET_KEY}'')\"`"; SALT="`curl -X GET http://localhost:8500/v1/kv/cloudconductor/parameters?token=${CONSUL_SECRET_KEY_ENCODED} | jq ''.[].Value'' | sed -e ''s/[^\"]*\"\([^\"]*\)\".*/\1/'' | base64 -d | jq ''.cloudconductor.salt'' | sed -e ''s/[^\"]*\"\([^\"]*\)\".*/\1/''`"; PASSWORD="`/opt/chefdk/embedded/bin/ruby -e \"require ''openssl''; puts OpenSSL::Digest::SHA256.hexdigest(''${SALT}'' + ''database'')\"`"; sudo -u mysql mysql -u application -p${PASSWORD} < /var/cloudconductor/backups/mysql/dump.sql) >/dev/null 2>&1'
      restore_enabled: true
  privileges:
    - user: mysql
      command: /usr/bin/mysql
    - user: mysql
      command: /usr/bin/mysqldump
