source "https://supermarket.getchef.com"

cookbook 'serf', git: 'https://github.com/bbaugher/serf.git', tag: '0.7.0'
cookbook 'yum-epel'
cookbook 'nginx'
cookbook 'rbenv'
cookbook "mysql"
cookbook 'iptables'
cookbook 'application'
cookbook 'application_ruby'
cookbook 'git'
cookbook 'puma'
