source "https://supermarket.getchef.com"

cookbook 'serf', git: 'https://github.com/bbaugher/serf.git', tag: '0.7.0'
cookbook 'consul', git: 'https://github.com/johnbellone/consul-cookbook.git'
cookbook 'yum-epel'
cookbook 'nginx'
cookbook 'rbenv'
cookbook "mysql"
cookbook "database"

