#!/bin/sh
# Copyright 2014 TIS Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CONDUCTOR_ROOT_DIR="/opt/cloudconductor"
CONDUCTOR_PATTERNS_ROOT_DIR="${CONDUCTOR_ROOT_DIR}/patterns"
CONDUCTOR_PATTERN_EVENTS_DIR="events"
PAYLOAD_DIR="temp"
PAYLOAD_FILE="payload.json"
PLUGINHOOK_FILE="/usr/local/bin/pluginhook"
CONFIG_FILE="/etc/profile.d/chef.sh"

if [ -f ${CONFIG_FILE} ]; then
  source ${CONFIG_FILE}  
fi

function read_payload() {
  while read payload; do
    echo "${payload}"
  done
}

payload="`read_payload`"

find ${CONDUCTOR_PATTERNS_ROOT_DIR} -maxdepth 1 -type d | egrep -v "^${CONDUCTOR_PATTERNS_ROOT_DIR}$" | while read pattern; do
  if [ "${SERF_EVENT}" = "user" ]; then
    EVENT="user-${SERF_USER_EVENT}"
  elif [ "${SERF_EVENT}" = "query" ]; then
    EVENT="query-${SERF_QUERY_NAME}"
  else
    EVENT=${SERF_EVENT}
  fi
  mkdir -p ${pattern}/${PAYLOAD_DIR}
  echo "${payload}" > ${pattern}/${PAYLOAD_DIR}/${PAYLOAD_FILE}
  export PLUGIN_PATH=${pattern}/${CONDUCTOR_PATTERN_EVENTS_DIR}
  ${PLUGINHOOK_FILE} ${EVENT}
done
