name             'cloudconductor_init'
version          '0.0.1'
description      'Installs/Configures cloudconductor_init'
license          'Apache v2.0'
maintainer       'TIS Inc.'
maintainer_email 'ccndctr@gmail.com'
supports         'centos', '= 6.5'

depends          'yum-epel', '~> 0.4.0'
depends          'serf', '~> 0.7.0'
depends          'consul', '~> 0.3.0'
